version: 0.0.{build}
before_build:
  - cmd: nuget restore
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}'
build:
  project: Seq.App.Pushover.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: wczgzVPerY0xIV4I0DuktKSvNaYIAMVK8Ei1875/fhgt7ZjahBy8hL5Q5ZN/h+2U
  on:
    branch: master