version: 0.0.{build}-dev
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}'
build:
  project: Seq.App.Pushover.sln
  verbosity: minimal